[package]
name = "wasm_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "*"
sdl2 = { version = "*", features = ["raw-window-handle"] }
pixels = "*"